# Generated by Django 2.2 on 2021-07-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_activa',
            new_name='is_active',
        ),
    ]
